matrix:
  VERSION:
    - "2.22"

build:
  a_preparing:
    image: armhfbuild/buildpack-deps:jessie-scm
    commands:
      - git clone --single-branch https://github.com/andyshinn/alpine-pkg-glibc upstream
      - mkdir packages
      - chown -R 1000 upstream packages
      - cd upstream
      - sed -i 's/arch=.*/arch="armhf"/g' APKBUILD
      - sed -i 's/ld-linux-x86-64.so.2/ld-linux-armhf.so.3/g' APKBUILD
      - sed -i 's/lib64/lib/g' APKBUILD
      - sed -i 's/^source=.*/source="https:\/\/github.com\/armhf-docker-library\/glibc\/releases\/download\/2.22\/glibc-bin.tar.gz/' APKBUILD
      - export MD5=2a9d468836dd45918d679ee53ae23542
      - sed -i "s/md5sums=\".*/md5sums=\"${MD5} glibc-bin.tar.gz/" APKBUILD
  b_building:
    image: armhfbuild/alpine-abuild
    environment:
      - RSA_PRIVATE_KEY=ABCDEF
    commands:
      - ln -s $PWD/upstream /home/builder/package
      - cd /home/builder/package
      - abuilder -r
      - cp /home/builder/packages/alpine-pkg-glibc/armhf/* /drone/src/github.com/armhf-docker-library/alpine-pkg-glibc/packages/

publish:
  github_release:
    api_key: $$GITHUB_API_KEY
    files: packages/*
    checksum: sha1

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
